### PR TITLE
Laravel 6.x compatibility

### PR DESCRIPTION
**Pull request by matthewnessworthy**

### CODE REVIEW

**Comment by matthewnessworthy** [comment]
@nikolajlovenhardt please review when you have a moment

**Comment by nikolajlovenhardt** [comment]
@matthewnessworthy Hi Matthew - unfortunately, I'm no longer a part of the organizations. I'd recommend that you fork the repository and maintain it yourself.

**Comment by matthewnessworthy** [comment]
Does that mean there's no longer any ongoing support for this project?

**Comment by nikolajlovenhardt** [comment]
@matthewnessworthy It seems so. Unfortunately, I no longer have access to maintain the project.

**Comment by matthewnessworthy** [comment]
@nikolajlovenhardt thanks for your help

**Pull request closed without merging**
